# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c18a28c91bfb77a4a344aabaac6223e3477fbf682b47446b40d612d095e492e8189f9058a94e7a26d1c633ee8ee5cdba2177cc8c725443e5b9436f8a0485702d

test:
  secret_key_base: 9d5574468518d7575b736c531a72b434b2904ddc25e904d45c6d20aac1f809593aa8fb0b4ca88fa5e233a47aa69e14f3f03503a93d6e3ab9dc23e25bcc72b198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
